version: '3.8'

services:
  tts-finetuner:
    image: ${DOCKER_IMAGE:-ghcr.io/mozi1924/qwen3-tts-easyfinetuning:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qwen3-tts-finetuner
    ports:
      - "7860:7860"
      - "6006:6006"
    volumes:
      - ./final-dataset:/workspace/final-dataset
      - ./output:/workspace/output
      - ./logs:/workspace/logs
      - ./models:/workspace/models
      - ./raw-dataset:/workspace/raw-dataset
      - ./src:/workspace/src

    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VLLM_USE_MODELSCOPE=true
      - HF_HOME=/workspace/models/huggingface
      - MODELSCOPE_CACHE=/workspace/models/modelscope
      - PYTHONUNBUFFERED=1
